apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: helm-demo
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      purpose: helm-demo
  template:
    metadata:
      labels:
        purpose: helm-demo
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
    
    
  
