apiVersion: v1
kind: Service
metadata:
  name: nginx-server

spec:
  type: {{ .Values.service.serviceType }}
  selector:
    purpose: helm-demo
  ports:
  - protocol: TCP
    port: {{ .Values.service.servicePort }}
    targetPort: 80
    nodePort: 30007